### ISSUE TITLE
how to resolve this error 8xD900458B ??

### ISSUE THREAD

**Issue by Fernandosv94** [FlagBrew/PKSM#1304] opened 2021-11-05 00:02 UTC
![WhatsApp Image 2021-11-04 at 19 55 01](https://user-images.githubusercontent.com/93551623/140436386-23f5f54b-23c1-4a62-84b0-d49339ece941.jpeg)

i upgraded my 3ds in the latest current version, luma etc... when I went to install PKSM 9.2.0 it loads and pops up error, how to solve ? checked and all the files are correct...

**Comment by GriffinG1** [comment] 2021-11-05 00:05
Duplicate of #1203

**Closed by GriffinG1** 2021-11-05 00:05 UTC
