### ISSUE TITLE
PKSM 7.0 save storage group

### ISSUE THREAD

**Issue by Supercam88** [FlagBrew/PKSM#1037] opened 2019-09-10 02:56 UTC
Everytime I try to save a storage group, and says some error and it doesn’t save box name or Pokemon I put in storage groups, and I have enough blocks on my sd card.

**Comment by GriffinG1** [comment] 2019-09-10 02:57
👏 tell 👏 us 👏 the 👏 error 👏 we 👏 aren't 👏 psychic 👏

**Comment by Supercam88** [comment] 2019-09-10 03:05
Error: 0xE0E046C7

**Comment by GriffinG1** [comment] 2019-09-10 03:10
I've seen it pop up from a couple users, I don't think @piepie62 found the cause yet though

**Comment by Supercam88** [comment] 2019-09-10 03:10
Oh ok

**Comment by GriffinG1** [comment] 2019-09-10 03:10
Wait until he comes back, and most importantly do not try to do anything before then.

**Comment by Supercam88** [comment] 2019-09-10 03:13
Ok

**Comment by piepie62** [comment] 2019-09-10 04:00
Could you dump your ExtData with Checkpoint and send the backup here zipped? Also, what's your 3DS system version?

**Comment by piepie62** [comment] 2019-09-10 16:47
This should be fixed by latest commits; it was an error having to do with the lengths of bank names.

**Comment by piepie62** [comment] 2019-09-11 05:44
Fixed by 7.0.1

**Closed by piepie62** 2019-09-11 05:44 UTC
