### ISSUE TITLE
Bug Report - Corrupted Pokédex Entries in Platinum

### ISSUE THREAD

**Issue by TheLenare** [FlagBrew/PKSM#1034] opened 2019-09-02 07:25 UTC
**Describe the bug**
When I mass-imported all my boxes from another save file into my Pokémon Platinum save file, multiple Pokédex entries were corrupted. When I attempt to view them on actual hardware, the game crashes. Viewing them with DeSmuME looks like this:
![Corrupt Entry](https://874ac2a6-a-62cb3a1a-s-sites.googlegroups.com/site/supahlorenenterprises/lenare-s-stuff/ice-cream-mod-1-8/corrupt_entry.png?attachauth=ANoY7coz1K681aiFy54RDxwPugmA9Phv_E89anBgLLRdb97NE8Ycob-3r2MV4nNjFo6f_tymkXU4VgbvX2rCvxq2y4ByxMq1MXGWUXj8gT8AbKYg9kLstd5abN7CpuPVOzzaD1hHS4FG9xLPCSzWbTvN8wjT_KV5faP4Dnq73sAvpPNoZnKbfTcrJqObfVGfugjDX_mBsfA_1_LOlWbeOGPPgBeEpfjpCFOb4fz0GYj4cgTrvTip4nmXL0cwI4Ibqbh3VIoV4bFlYizeJVdZANhjwgCMndzpPQ%3D%3D)

**To Reproduce**
Attached is my save file. Importing the all the boxes currently on it is what caused the issue, I tried it on a fresh save (forcing the national dex to unlocked) with the same result.
[POKEMON PL.zip](https://github.com/FlagBrew/PKSM/files/3564867/POKEMON.PL.zip)

**Information about your environment**
 - OS version: 11.10.0-43U
 - PKSM version: 6.2.1
 - Entrypoint: CFW

EDIT: The "other save file" I imported these boxes from was Soul Silver. Realized that might be important.

**Comment by piepie62** [comment] 2019-09-02 07:32
I'm fairly certain I've already fixed this. I'll make sure later today

**Comment by marcelothebuilder** [comment] 2019-09-03 02:55
I also had this problem today. Same OS, same PKSM version, same entrypoint and surprisingly the same games (from SoulSilver to Platinum)

**Comment by GriffinG1** [comment] 2019-09-03 03:06
you wouldn't have the fix, if it was done, because the fix would be in a bleeding edge builds. wait for 7.0.0. No release date.

**Comment by piepie62** [comment] 2019-09-03 03:23
It appears I have not, however, I can't tell exactly what is wrong. @Admiral-Fish might know better

**Comment by marcelothebuilder** [comment] 2019-09-03 03:36
This is my savefile. Hope it helps. I was able to transfer successfully using PKHEX, through a process that I found much less user-friendly :/
[Pokemon_Platinum.zip](https://github.com/FlagBrew/PKSM/files/3567651/Pokemon_Platinum.zip)

**Comment by piepie62** [comment] 2019-09-03 07:31
Strangely enough, it seems that the code *was* fixed. Injecting a new Pokémon does work, but overwriting old, broken entries doesn't fix them.

**Comment by zener88** [comment] 2019-09-05 08:45
Same happened to me some time ago. The issue is that if you set an only-female pokemon into male, the pokedex entry is going to crash.  Same if you set a only-male pokemon into a female. It happened to me with Vespiquen and it seems you have the same problem with Kangaskhan. If you use the script for fill the whole pokedex, the issue will solve.

**Comment by piepie62** [comment] 2019-09-05 16:31
Alright, just figured out why it doesn't get fixed by overwriting things. It's actually an intended thing; we don't overwrite entries that already exist. As the problem's source is fixed and there is an easily accessible fix to the symptoms, I'm considering this issue solved

**Closed** 2019-09-08 21:41 UTC
Labels: fixed
