### ISSUE TITLE
Bug Report-Black Screen after open PKSM 6.0

### ISSUE THREAD

**Issue by kuai18** [FlagBrew/PKSM#834] opened 2019-01-01 12:37 UTC
**Describe the bug**
After open PKSM 6.0, the 3DS display black screen and no responding.

**To Reproduce**
1. Open PKSM 6.0 on the main interface of 3DS
2. 3DS display 'homebrew'
3. 3DS display black screen with nothing, and it is no responding
4. I must forced shutdown 3DS

**Information about your environment**
 - OS version: 11.9.0-42J (Luma 7.1)
 - PKSM version: 6.0.0
 - Entrypoint: CIA

**Comment by kuai18** [comment] 2019-01-01 14:57
No matter I insert my R4i flashcart or not, the issue happens.

**Comment by Volti-Z** [comment] 2019-01-01 14:58
Do you have the Internet Connection on? You Need to download the assets from the 3DS to get PKSM to work.

**Comment by kuai18** [comment] 2019-01-01 14:59
I have the Internet Connection, PKSM 5.1.4 is work

**Comment by World-King** [comment] 2019-01-02 06:02
I'm also experiencing the same problem here. Start PKSM, black screen and nothing else. My GF's 3DS runs PKSM normally, but mine doesn't!

**Comment by fatburd** [comment] 2019-01-02 17:00
Same issue here, although I can see the PKSM main menu for a brief second before it crashes.

Exception type: data abort
Fault status: Permission - Page

I saved the crash dump, if it is of any use.

**Comment by kuai18** [comment] 2019-01-03 13:42
@BernardoGiordano I find 'gui.json' file is missing in JP\ZH\KO localization folders. My 3DS is Janpan console and language I set in PKSM is Chinese. Is it the reason caused this issue?

**Comment by BernardoGiordano** [comment] 2019-01-03 13:44
Thisisnot an issue. JP/ZH/KO people didn't help us translating the localization files yet, that's why we don't have those. Feel free to help if you're a native speaker for one of those languages

**Comment by kuai18** [comment] 2019-01-03 13:51
@BernardoGiordano I'd like to translate the Chinese  localization file. 
Besides, the question I just asked is whether 'gui.json' file missing will cause black screen when PKSM boot on Japan 3DS console.

**Comment by BernardoGiordano** [comment] 2019-01-03 14:04
Oh, nope, it's not related to that in any way. Please have a look at this build here and tell me how that goes https://www.dropbox.com/s/zzd4ty8loa9segm/PKSM.7z?dl=0

**Comment by kuai18** [comment] 2019-01-03 14:16
@BernardoGiordano I tried this build, the same problem still exists.

**Comment by BernardoGiordano** [comment] 2019-01-03 14:17
Do you have files into your `sdmc:/3ds/PKSM/assets` folder?

**Comment by kuai18** [comment] 2019-01-03 14:20
No 'assets' folder in sdmc:/3ds/PKSM/, only 'additionalassets' folder in it

**Comment by BernardoGiordano** [comment] 2019-01-03 14:21
put these two files into the `assets` folder. Create one if it's not there

https://github.com/dsoldier/PKResources/tree/master/additionalassets

**Comment by kuai18** [comment] 2019-01-03 14:38
I am using old version FBI(1.4.17),it hasn't exdata browser. I will update it tomorrow, then tell you the result.

**Comment by fatburd** [comment] 2019-01-03 14:59
> mmh I think this is a situation where PKSM is not able to create the extdata archive on your console. Please boot FBI, go to the extdata browser and delete the extdata archive for PKSM (should be called PKSM or 0x00...0EC100). If it doesn't exist, please tell us.

Just tried it, it existed and I deleted it, but at least here the same error came up.

**Comment by BisharpKicker** [comment] 2019-01-03 15:09
> mmh I think this is a situation where PKSM is not able to create the extdata archive on your console. Please boot FBI, go to the extdata browser and delete the extdata archive for PKSM (should be called PKSM or 0x00...0EC100). If it doesn't exist, please tell us.
> 
> then, try booting it up again.
> 
> If this doesn't solve the issue yet, we may need to debug this issue in a debug environment set up ad hoc for you. This is a nasty bug

I did not find the archive it does not exist in mine

**Comment by BernardoGiordano** [comment] 2019-01-03 15:13
@fatburd @BisharpKicker are you entirely sure that you also don't have a flashcart inserted, you have internet available and you're using the build I linked?

**Comment by BisharpKicker** [comment] 2019-01-03 15:17
> @fatburd @BisharpKicker are you entirely sure that you also don't have a flashcart inserted, you have internet available and you're using the build I linked?

Yes but I just added the assets archives and will boot it up once more

**Comment by BisharpKicker** [comment] 2019-01-03 15:22
> > @fatburd @BisharpKicker are you entirely sure that you also don't have a flashcart inserted, you have internet available and you're using the build I linked?
> 
> Yes but I just added the assets archives and will boot it up once more

Just did this, it still crashes.


> @fatburd @BisharpKicker are you entirely sure that you also don't have a flashcart inserted, you have internet available and you're using the build I linked?

Thanks for the help btw

**Comment by BernardoGiordano** [comment] 2019-01-03 15:24
can you provide info about your system?

**Comment by BisharpKicker** [comment] 2019-01-03 18:14
I downgraded to 5.1.4 and it works just fine

**Comment by RPGFAN128** [comment] 2019-01-03 19:46
After reading all of the suggestions I first checked out my extdata/0...0/...EC100/0...0/ folder to see it contained two files 0...01 and 0...02 both modified 1/1/2019 3:15 pm (time of the crash).  So I didn't delete these, I only changed one thing -- adding folder pksm/assets/ and adding the two files listed above.  Again I have nothing inserted in the card slot and no internet period.  This one changed allowed a successful boot.  I have provided my setup for possible debugging purposes.

Firmware.  11.8 (North America)
Entry -- CFW + installed CIA
Luma 9.1
FBI + Checkpoint + PKSM -- Latest
Model -- new 3DS.  

One critique I have is the following.  Even though I completely read the v6.0.0 documentation nothing was mentioned about a way to manually add (evidently REQUIRED) assets.  It would perhaps be a good idea to add this in the "manual installation" -- that is if someone has already manually put the CIA file onto their SD card it is a prime time to add required assets also.  

One suggestion I would have to adhere to good programming practices is the following.  Any new user who does not have internet or their 3DS' internet is simply turned off the program indefinitely hangs attempting to go online.  If the program prompted the user to "attempt to connect to internet to download assets?" then they could (A) choose not to at this time or (B) try to connect and then it would similar be very easy to see where the problem arises.  Instead of trying to figure out where the problem is a non-programmer could easily describe "the program launched but it froze when I tried to connect to the internet."  Similarly, even a non-programmer would be able to deduce this and then trouble-shoot themselves (without cluttering up github issues) for example trying to activate their internet or get to a place where they could use internet.  (Unfortunately the entire world does not have internet...)

In closing I hope my blunt-to-the-point communication doesn't hurt anyone's feelings.

**Comment by kuai18** [comment] 2019-01-04 12:50
> mmh I think this is a situation where PKSM is not able to create the extdata archive on your console. Please boot FBI, go to the extdata browser and delete the extdata archive for PKSM (should be called PKSM or 0x00...0EC100). If it doesn't exist, please tell us.
> 
> then, try booting it up again.
> 
> If this doesn't solve the issue yet, we may need to debug this issue in a debug environment set up ad hoc for you. This is a nasty bug

Extdata of PKSM doesn't exist.

**Comment by BernardoGiordano** [comment] 2019-01-04 17:57
@kuai18 please test this build and let me know which error code appears on screen https://www.dropbox.com/s/zzd4ty8loa9segm/PKSM.7z?dl=0

**Comment by BisharpKicker** [comment] 2019-01-04 18:44
> @kuai18 please test this build and let me know which error code appears on screen https://www.dropbox.com/s/zzd4ty8loa9segm/PKSM.7z?dl=0

should I test it as well?

**Comment by BisharpKicker** [comment] 2019-01-04 18:58
I just tried booting and something different has happened, it says error during startup 0xD88007FA

**Comment by BernardoGiordano** [comment] 2019-01-04 19:01
@BisharpKicker which message does it say? Please provide the whole error log

**Comment by BernardoGiordano** [comment] 2019-01-04 19:30
Do you have boot9strap? Do you have latest luma3ds? That's the issue

**Comment by BisharpKicker** [comment] 2019-01-04 20:22
> Do you have boot9strap? Do you have latest luma3ds? That's the issue

thanks for the help it seems as if I cannot update the luma3ds so I will just downgrade back to 5.1.4

**Comment by deadair3210** [comment] 2019-01-04 21:02
Why can you not update luma? Maybe someone can point you in the right direction

**Comment by kuai18** [comment] 2019-01-05 04:30
@BernardoGiordano I tried this build, and get same error message as BisharpKicker.
Error during startup:0xD88007FA
Description:Rosalina sysnodule has not been found make sure you are running latest luma3ds

I am using boot9strap 1.0+luma3ds 7.1 now. Maybe I need to upgrade to boot9strap 1.3+luma3ds 9.1

**Comment by BernardoGiordano** [comment] 2019-01-05 04:55
Yes you need. I consider this issue fixed

**Closed by BernardoGiordano** 2019-01-05 04:55 UTC
