### ISSUE TITLE
Gitarina bug

### ISSUE THREAD

**Issue by paf2014** [FlagBrew/PKSM#1148] opened 2020-04-01 04:40 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'pksm'
2. Click on 'absent games'
3. go to any boxes

**Expected behavior**
All sprites of the menu of absent games and boxes from all my savs and boxes turned into giratina altered form although they are not all giratinas after editting my gen 5 game sav.
![fi](https://user-images.githubusercontent.com/46760859/78099905-b6b9df00-73b9-11ea-9376-16b9b7407b00.png)

**Screenshots**

**Information about your environment**
 - OS version:last
 - PKSM version:last
 - Entrypoint:cia installed

**Additional context**

**Comment by SpiredMoth** [comment] 2020-04-01 04:41
Duplicate of #1147

**Closed by SpiredMoth** 2020-04-01 04:41 UTC

**Comment by SpiredMoth** [comment] 2020-04-01 19:37
Please open a new issue instead of editing an unrelated one that has already been closed
