### ISSUE TITLE
First CMAC is invalid Pokémon Emerald Spanish

### ISSUE THREAD

**Issue by Labestiajake** [FlagBrew/PKSM#1284] opened 2021-07-11 21:15 UTC
**Describe the bug**
The error is in Pokémon Emerald in Spanish language, the error say First CMAC is invalid and i press A. PKSM load previous save, but if i press B and press A, load fine.

**To Reproduce**
1. Open PKSM
2. Click Button R fast and move fast to Pokémon Emerald
3. See error

**Expected behavior**
It only happens with the emerald pokemon if it is done quickly. If you do it slowly the error appears randomly (every 20-25 appears one). If this happens, load a previous save game.

**Screenshots**
<img src="https://i.ibb.co/zfxG8YR/CMAC.png" alt="CMAC" border="0">

**Information about your environment**
 - OS version: 11.14.0-46E
 - PKSM version: v9.20.-656eb68a
 - Entrypoint: Luma CFW v10.2.1

**Comment by piepie62** [comment] 2021-07-12 04:59
This one is a really interesting bug. My best guess is that it's caused by one of two things: a race condition (with two processes accessing FSPXI instead of one) or the FXPXI service's seeming faultiness (Nintendo's filesystem module code calls the method I use up to twenty times to check if the returned data matches a second call). I've been trying to avoid fixing this with a loop, but I haven't found anything yet. I'll toss up a commit that does it for the next version while looking for a better way. Thanks for the report

**Comment by raul-792** [comment] 2022-08-17 08:00
![image](https://user-images.githubusercontent.com/111419858/185065818-1c10c330-3cfa-4c7d-aa49-011ef01e4c1a.jpg)
Error pksm esmerald version 
An exeption has ocurred during execution.
How to load a save file??

**Comment by raul-792** [comment] 2022-08-17 08:01
![image](https://user-images.githubusercontent.com/111419858/185066605-2db4c0b3-ea1e-44a5-b4cf-3c4b0a65b7d6.jpg)

**Comment by GriffinG1** [comment] 2022-08-17 08:06
@raul-792 Please open up your own issue instead of posting on other, vaguely related, issues. Thanks.

**Comment by GriffinG1** [comment] 2023-03-26 18:24
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).

**Closed by GriffinG1** 2023-03-26 18:24 UTC
Labels: bug, fixed
