### ISSUE TITLE
Bug Report (Crashing entire 3ds soon after loading PKSM)

### ISSUE THREAD

**Issue by turtleisaac** [FlagBrew/PKSM#832] opened 2019-01-01 06:09 UTC
**Describe the bug**
After launching PKSM, I reach the game select screen and the music starts playing. However, within a second or two, the system crashes and sends me to the "An exception occurred screen". I am told to press A to save the crash dump, and press any other button to shutdown. The Exception type is data abort, Fault status is Permission - Page, and Current process is PKSM (000400000EC10000).

**To Reproduce**

Launch PKSM from the home menu
Program loads to game select screen, music starts to play
Program crashes, sends me to screen mentioned/ described above

**Expected behavior**
I expect for the program to work and allow me to edit/ modify saves

**Screenshots**

![img_6121](https://user-images.githubusercontent.com/7987859/50570662-5c1e7700-0d61-11e9-8567-a2eeb4ef7a3d.jpg)

![img_0459](https://user-images.githubusercontent.com/7987859/50570663-5e80d100-0d61-11e9-8195-92128f8cd09f.jpg)

**Information about your environment**
 - OS version: Ver 11.7.0-40U, Luma3DS 9.1
 - System: o3Ds XL  ( SPR-001(USA) )
 - PKSM version: 6.0.0
 - Entrypoint: Home menu, installed using .cia and FBI

**Additional context**
I was able to get a successful launch just minutes before this error appeared. During this session, I took a Charizard set to be the Y form out of storage and put it into a PC box in my digital version of Ultra Sun. I got this permanent Y form Charizard by making it in pkhex and using servepkx to send it over to PKSM (Did this a few months ago, however the program would not allow me to place said Charizard into game. It did work this time, however) I launched Ultra Sun, put the Charizard in my party, and used it in battle twice. Saved, exited, and went back to PKSM to do some stuff. At this point, it crashes. I have tried to start it multiple times, all with the same result.

**Comment by turtleisaac** [comment] 2019-01-01 06:16
Update: restarting Ultra Sun made the Charizard Y revert to a normal Charizard (if that helps)

**Comment by turtleisaac** [comment] 2019-01-01 06:34
Update 2: Tried reinstalling PKSM with .cia and FBI, lasted a bit longer in the program before crashing. Otherwise, it's exactly the same

**Comment by BernardoGiordano** [comment] 2019-01-01 07:05
Please provide your save file here

**Comment by piepie62** [comment] 2019-01-01 07:06
A crash dump could also be helpful

**Comment by Ninjistix** [comment] 2019-01-01 14:08
seems likely that this is also a duplicate of #826

**Comment by turtleisaac** [comment] 2019-01-01 17:01
> seems likely that this is also a duplicate of #826

Yeah, it would seem so, just woke up and read #826 . I had an R4i card in my 3ds last night every time I started the application yesterday (even the time that it worked.) Took it out, program launched just fine with no errors to be seen. I'll attach the crash dump file so you guys can work it out when you get a chance (i have no idea what any of it means)

https://drive.google.com/file/d/1dBvP9lgm5MmCR_qN0tcGYNmRj8PTQVIH/view?usp=sharing

> Please provide your save file here

Do you mean my Ultra Sun save file?

**Comment by turtleisaac** [comment] 2019-01-01 17:19
Also, can the form option in the hex editor be changed to not be grayed out (byte 0x1D) It would be nice to change forms of Pokémon to have them be permanent mega’s, primal’s, etc...

Note: This is not for any competitive use. The Ultra Sun save file on this 3ds is a branch off of my cartridge save file. Cartridge is used for legitimate stuff and online activities on my new ds, digital version on this 3ds is for messing around with the game

**Comment by BernardoGiordano** [comment] 2019-01-01 19:20
Yes, send me the save file you're having issues with

**Comment by turtleisaac** [comment] 2019-01-01 19:57
I think it was a one-time thing; I cloned the Charizard out of the bank into the game again and it seems to be still in the Y form after using it and exiting out of the game

**Comment by BernardoGiordano** [comment] 2019-01-01 20:00
So, is the issue fixed? Was it because of the flashcard? So that I can safely close this issue.

**Comment by turtleisaac** [comment] 2019-01-01 20:02
yes, i believe it is fixed. Also i just realized i can click on the charizard in the editor and set the form. nice. Thanks though!

**Closed** 2019-01-01 20:02 UTC

**Comment by turtleisaac** [comment] 2019-01-01 20:05
And i immediately found a new error. yay.

**Comment by BernardoGiordano** [comment] 2019-01-01 20:05
Open a new issue.
