### ISSUE TITLE
Bug Report - Changing to a locked box in PKSM changes the box in-game, causing an error when opening the PC.

### ISSUE THREAD

**Issue by drewcorvec** [FlagBrew/PKSM#1257] opened 2021-03-03 23:06 UTC
**Describe the bug**
After the selected box is shifted to an out-of-bounds one in PKSM, the PC will lock up as soon as it's opened in-game.

**To Reproduce**
1. Open a save file in PKSM (only Black 2 tested)
2. Go to PC
3. Tab to a locked box (Only boxes 1-8 or 1-16 are unlocked before certain criteria)
4. Save the game using PKSM
5. Close PKSM and open the cartridge/ROM
6. Once in the overworld, find a PC and open its "Move Pokemon" or similar function
7. See error

**Expected behavior**
PKSM checks whether the selected box is unlocked. If it is, allow the file to save. If not, it changes the box to a different one and notify the user of the change.

**Information about your environment**
 - OS version: 11.14.046U
 - PKSM version: v9.2.0-656eb68a

**Comment by GriffinG1** [comment] 2021-03-03 23:15
Can't reproduce in ORAS on latest commits. Leaving box 31 (even with a pokemon in it) only blocks me from reentering that box, which makes sense because it's not unlocked yet.

**Comment by drewcorvec** [comment] 2021-03-03 23:19
So, just to be clear, you left while in box 31, and saved, correct?

**Comment by GriffinG1** [comment] 2021-03-03 23:21
Mhm.

**Comment by drewcorvec** [comment] 2021-03-03 23:23
Perhaps it's a bug with using the software with Black 2.

**Comment by GriffinG1** [comment] 2023-03-26 18:33
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).

**Closed by GriffinG1** 2023-03-26 18:33 UTC
Labels: bug, fixed
