### ISSUE TITLE
Event pokemon database error message

### ISSUE THREAD

**Issue by southboston** [FlagBrew/PKSM#1146] opened 2020-03-29 07:00 UTC
When i try to bring up the events on ultra moon i get this error message that i provide in the picture that i had taken.
![20200329_024722](https://user-images.githubusercontent.com/18722400/77843248-487edd80-7169-11ea-99f8-3b175bbd5d67.jpg)

**Comment by piepie62** [comment] 2020-03-29 07:16
What is in your `/3ds/PKSM/mysterygift` directory?

**Comment by southboston** [comment] 2020-03-29 22:29
Absolutely nothing, might be why im getting that error message lol.

**Comment by southboston** [comment] 2020-03-29 22:30
Should i uninstall then reinstall?

**Comment by piepie62** [comment] 2020-03-29 22:40
That will do nothing. What is your auto-update setting set to?

**Comment by southboston** [comment] 2020-03-30 01:06
It was on and then i turned it off, if i need it to be on then ill change it back.

**Comment by piepie62** [comment] 2020-03-30 02:12
WAIT, I just remembered what caused this in another user. What is your bank size?

**Comment by piepie62** [comment] 2020-03-30 02:12
Also turn it on, I was thinking you had it off

**Comment by southboston** [comment] 2020-03-31 01:00
On one of them its at 2000 and the others are all the same, and alright ill turn it back on and keep it on.

**Comment by piepie62** [comment] 2020-03-31 02:51
That's the problem, then. Recentlyish (when I added multibank support), I shrunk the maximum down to 500. Overlarge banks are still grandfathered in, but that is an issue that is known to be caused by them: the gifts stop working. If you have Pokémon in boxes 501-2000, DON'T just resize the bank to 500. Instead, move them all to the first 500 boxes, then resize

**Comment by southboston** [comment] 2020-03-31 21:32
Alrighty and after i do that what do you think i should to be able to get the mystery gift database to work again?

**Comment by piepie62** [comment] 2020-04-01 02:22
Yes, that should fix it.

**Comment by piepie62** [comment] 2020-04-05 05:06
As it's been four days, I'm going to assume this was fixed by my suggestion.

**Closed by piepie62** 2020-04-05 05:06 UTC

**Comment by AvarageUMenjoyer** [comment] 2022-12-19 16:15
where the heck can i find the bank that you guys talked about
