### ISSUE TITLE
"A" not working

### ISSUE THREAD

**Issue by marcossxx** [FlagBrew/PKSM#1324] opened 2022-06-18 12:51 UTC
"A" button does nothing and i can't select games

**Comment by GriffinG1** [comment] 2022-06-18 12:52
Cannot reproduce with this little info, please provide more.

**Comment by GriffinG1** [comment] 2022-06-20 07:47
I will be closing this in a week if no further details are provided.

**Comment by GriffinG1** [comment] 2022-06-27 10:47
Closing due to inactivity. Please open a new issue and properly fill out the template if you would like further help with this.

**Closed by GriffinG1** 2022-06-27 10:47 UTC
Labels: invalid
