### ISSUE TITLE
Error Giratina Icons

### ISSUE THREAD

**Issue by Vaztha** [FlagBrew/PKSM#1151] opened 2020-04-01 19:32 UTC
All icons are Giratina
I reinstall the game and change the folders, but nothing.
I have the latest version and I play pokemon ultra sun and i have a pokemon perl and Platin version
Plis help!!

**Comment by piepie62** [comment] 2020-04-01 19:33
Duplicate of #1147

**Closed by piepie62** 2020-04-01 19:33 UTC
