### ISSUE TITLE
[Bug Report] Version 6.0.0 crashing upon boot

### ISSUE THREAD

**Issue by fdaslkdafslkj** [FlagBrew/PKSM#831] opened 2019-01-01 05:48 UTC
PKSM crashes with red on bottom screen

When I try to open PKSM 6.0 through homebrew launcher or through the app downloaded via the .cia file, it crashes. I downgraded back to 5.1.4 and I experienced no problems.

 - OS version: 11.2.0-35U
 - PKSM version: 6.0.0

**Comment by turtleisaac** [comment] 2019-01-01 05:55
Try updating Luma. It was crashing for me until I updated to 9.1

**Comment by GriffinG1** [comment] 2019-01-01 06:11
*hax is no longer supported. Use Rosalina or cia.

**Comment by turtleisaac** [comment] 2019-01-01 06:13
> *hax is no longer supported. Use Rosalina or cia.

He said he tried through the app downloaded via the .cia file

**Comment by GriffinG1** [comment] 2019-01-01 06:15
Are you connected to WiFi? PKSM downloads assets at first launch.

**Comment by Ninjistix** [comment] 2019-01-01 14:08
seems likely that this is also a duplicate of #826

**Comment by BernardoGiordano** [comment] 2019-01-02 14:42
Closing as this is a duplicate of #826

**Closed by BernardoGiordano** 2019-01-02 14:42 UTC
