### ISSUE TITLE
[Bug Report] crashing upon launch /w flashcart

### ISSUE THREAD

**Issue by Ninjistix** [FlagBrew/PKSM#830] opened 2019-01-01 03:37 UTC
**Describe the bug**
application crashes system upon launching PKSM with a flash cart inserted.

**To Reproduce**
1. insert flashcart into system
2. launch pksm
3. application crashes 3ds.
[crash_dump_00000000.zip](https://github.com/FlagBrew/PKSM/files/2719098/crash_dump_00000000.zip)

**Expected behavior**
1. expected it to open so i can browse and edit my saves.

**Screenshots**
![img_20181231_222311](https://user-images.githubusercontent.com/12572974/50570248-861b6d80-0d50-11e9-88d9-ae1115d7f137.jpg)

**Information about your environment**
 - OS version: sys 11.9.0-42U
 - PKSM version: 6.0.0
 - Entrypoint: Luma 9.1

**Additional context**
I removed my flashcart and was successfully able to open pksm.

this is my flashcart, not sure if other's are affected or unaffected.
![image](https://user-images.githubusercontent.com/12572974/50570159-dba14b80-0d4b-11e9-863f-875f55a7c9b5.png)

edit: added better quality screenshot.

**Comment by deadair3210** [comment] 2019-01-01 07:00
Same card that I am talking about in the issue that I filed

**Comment by piepie62** [comment] 2019-01-01 07:03
Closing because it is a duplicate of #826

**Closed by piepie62** 2019-01-01 07:03 UTC
