### ISSUE TITLE
Events tab crashing with gen 6 files

### ISSUE THREAD

**Issue by kattoleen** [FlagBrew/PKSM#1352] opened 2022-12-08 20:15 UTC
I opened PKSM with my save file of Alpha Sapphire and pressing the Events/Mystery Gift tab generates an error and the app crashes. It also happened with my Y save file, but not with Ultra Moon. My PSKM version is v9.2.0-656eb68a. Running on an Old 3ds, sys ver 11.16.0-49U
![IMG_20221208_171432412_HDR](https://user-images.githubusercontent.com/120135690/206558615-70af077a-a183-4ba9-a90b-e413be4a4133.jpg)

**Comment by unxw** [comment] 2022-12-09 16:25
I have the same issue for my gen 8 save, it used to work before. I am going to reinstall, and I will see if that fixes anything.

**Comment by MasterOfNone123** [comment] 2022-12-10 20:53
Yeah, I've got this same issue happening with my Moon save. Managed to inject 2-3 events earlier and then this just started happening today.

**Comment by Jaxonos** [comment] 2022-12-15 01:28
I got the same error here with gen 7 (pokemon sun), after installing an update to the mystery gift cards.

**Comment by amanda-chill** [comment] 2022-12-17 19:20
yeah, pksm wont let me see the events in smusum, i didnt really do anything.

**Comment by SusVulpix** [comment] 2022-12-23 18:49
I am having the same exact problem. I haven’t been on PKSM for a while, and I check on it yesterday, and it is the same problem for “Events.” I am glad I am not the only one. I hope you guys are able to fix this bug. Merry Christmas, everyone😁

**Comment by SusVulpix** [comment] 2022-12-25 16:59
When do you guys think the bug will be fixed?

**Comment by kattoleen** [comment] 2022-12-26 15:20
it somehow fixed itself? i didn't open the wondercards tab until today and surprise, it didn't crash this time.
i even tested it and injected the XY promo Torchic + blazikenite and it worked!
![IMG_20221226_121620755](https://user-images.githubusercontent.com/120135690/209562944-003163a2-afe5-4022-a5cd-d7bcd5f84d1e.jpg)

anyways, i'm not closing this thread as probably many of you still have the issue.
happy holidays everybody <3

**Comment by SusVulpix** [comment] 2022-12-26 17:38
Yay!! Thank you for telling me this, and responded to me. Happy holidays, and a happy New Year!!! 😁😁😄

**Comment by SusVulpix** [comment] 2022-12-26 17:49
It's still not working for me. ![image](https://user-images.githubusercontent.com/121309298/209572900-3f681b73-4059-48b9-8566-5e5281c38114.jpeg)

**Comment by SusVulpix** [comment] 2022-12-26 17:49
It's still not working for me ![image](https://user-images.githubusercontent.com/121309298/209572923-f75945a1-0986-423e-8132-9cd6230db670.jpeg)

**Comment by SusVulpix** [comment] 2022-12-26 18:45
Can anyone tell me how to fix, or tell me who will be fixing the bug.

**Comment by Zabbrielle** [comment] 2022-12-28 19:41
I had this issue and it seemed to fix itself after rebooting my 3ds a few times.

**Comment by SusVulpix** [comment] 2022-12-28 19:43
Im going to sound like an idiot, but can you tell me how to reboot my Homebrew 3ds? Thank you for responding to my comment.

**Comment by SusVulpix** [comment] 2022-12-28 21:34
Is it still showing you that it is still updating, and that's it is updating gift database 5 of 6, or 7 of 8?

**Comment by Jaxonos** [comment] 2023-01-01 00:07
I am now having this issue on the gen 5, event tab.

**Comment by FM1337** [comment] 2023-01-08 19:49
Could I request anyone experiencing this issue, to launch PKSM while connected to the internet and try this again? I suspect I know what's going on and pushed a server fix to hopefully address it.

**Comment by SusVulpix** [comment] 2023-01-08 19:50
I turned off auto save, so that I don't have to deal with the issue. Do you want me to turn it back on?

**Comment by FM1337** [comment] 2023-01-08 19:51
Auto save shouldn't impact this.

**Comment by SusVulpix** [comment] 2023-01-08 19:51
sorry, not auto save, auto update

**Comment by FM1337** [comment] 2023-01-08 19:51
yes please turn on auto update

**Comment by SusVulpix** [comment] 2023-01-08 19:54
I see no sign of that error. I also see that it is not showing updated gift database 5 of 6, or 7 of 8

**Comment by SusVulpix** [comment] 2023-01-08 19:58
Thank you for fixing the bug for us.😁👍 Have a great 2023.

**Comment by FM1337** [comment] 2023-01-12 22:45
Since there's been no one saying otherwise, I'm going to mark this as fixed.

**Comment by GriffinG1** [comment] 2023-03-26 18:24
Fixed in [v10](https://github.com/FlagBrew/PKSM/releases/latest).

**Closed by GriffinG1** 2023-03-26 18:24 UTC
Labels: bug, fixed

**Comment by jack8-boop** [comment] 2025-08-16 21:26
Hey did this effect ur games ability to generate shiny legends from wormhole This happened to me and I haven’t had a shiny legendary since?

**Comment by GriffinG1** [comment] 2025-08-16 21:42
@jack8-boop please stop replying to closed, unrelated issues. Further, that is not something that could be caused by PKSM. Locking this issue.
