### ISSUE TITLE
Bug Report - Every pokemon became egg 

### ISSUE THREAD

**Issue by marcocc1234** [FlagBrew/PKSM#1267] opened 2021-04-08 14:48 UTC
I have a problem with PKSM, when I go to generate any pokemon of any level, I am only recognized as an egg, in all GBA games (fire red, sapphire, etc.)
![76CB76BA-98E6-4164-86CE-39CC19287E00](https://user-images.githubusercontent.com/82165426/114047694-2a72af80-988a-11eb-98a1-a8ed9cd3df20.jpeg)

**Comment by piepie62** [comment] 2021-04-08 20:28
This seems like it's related to #1261. Could you try the steps mentioned there and see if that fixes it for a single time opening PKSM afterwards?

**Comment by marcocc1234** [comment] 2021-04-08 21:31
I tried to follow the steps but unfortunately also the first time has the same error.  maybe I did something wrong

**Comment by marcocc1234** [comment] 2021-04-09 15:16
Is there anyone who knows what to do?

**Comment by delhunter** [comment] 2021-04-15 23:55
I am having the same issue where it only seems to affect the gba titles. Tried the solution that was linked to but it didn't fix the problem.

**Comment by segacdboy15** [comment] 2021-09-25 01:36
I just installed this today and I'm having that exact issue I hope they fix it soon

**Comment by GriffinG1** [comment] 2022-09-16 22:25
This cannot be reproduced on the latest commits, so I'm going to assume that it was linked to #1261, and close this. Once the next version releases (there is no ETA), please delete your pk3 default file and see if the issue is solved. If it is not, follow up on this issue and I will reopen it.

**Closed by GriffinG1** 2022-09-16 22:25 UTC
Labels: bug
