### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lucid999** [FlagBrew/PKSM#909] opened 2019-02-01 17:27 UTC
**Is your feature request related to a problem? Please describe.**
If you're genning a Pokemon, it gens the mon from scratch so it's unlegit and you need to make it legit manually in the hex editor. It efforts too much time and lots of user don't know how to handle with the hex editor.

**Describe the solution you'd like**
You should add that PKSM is generating a legit Pokemon template, so you don't need to do the things in the hex editor.

**Additional context**
I'd be great if you guys could add this because in the further version PKSM was genning a legit Pokemon template.

**Comment by TLATER** [comment] 2019-02-10 13:51
Could you make the title "Feature Request: Use legitimate Pokemon templates"?

That way people don't need to click on your issue to know what it's about when they're double checking if they're about to create a duplicate issue.

You'll also find that this is a duplicate of #907.

**Closed** 2019-02-10 14:59 UTC
