### ISSUE TITLE
Bug Report - Music is broken

### ISSUE THREAD

**Issue by obscurerev** [FlagBrew/PKSM#1290] opened 2021-08-05 19:51 UTC
**Describe the bug**
Music listed in the Songs folder in the sdmc:/3ds/PKSM directory only plays for a split second before cutting completely.

**To Reproduce**
1. Open PKSM
2. Wait for it to load
3. Music plays for a split second.
4. Music cuts and everything else loads normally.

**Expected behavior**
Plays music normally upon entering the save menu.

**Information about your environment**
 - OS version: 11.15 (North America)
 - PKSM version: 9.2.0
 - Entrypoint: Luma3DS and/or B9DS or something like that

**Additional context**
I have dumped the latest DSP1, I have tried renaming the file to something without any special characters and have tried putting multiple .mp3 files in the folder. All to no avail.

**Comment by Mewthree3** [comment] 2021-08-05 19:57
I’ve had a similar issue—but I had a bunch of files in it. Do your music files have Japanese naming on them? This homebrew I use for switch doesn’t support Japanese so I had to rename files in order to play them.

**Comment by obscurerev** [comment] 2021-08-05 20:01
There's no Japanese characters on mine. Does yours work with or without an author listed? I used 3DShell to view the mp3 and it has an artist name.

**Comment by Mewthree3** [comment] 2021-08-05 20:07
They were mostly without author names, although one (your adventure by okazaki taiiku), had an author name. It didn’t play as well—(I moved the mp3s to my switch a few months ago, and they play fine using a sysmodule mp3 player, so anything would be on PKSM’s end)—so I assume artist names wouldn’t mess with playback.

**Comment by obscurerev** [comment] 2021-08-05 20:09
So artist names don't have to do with this huh...? I don't know what could be causing it otherwise.

**Comment by Mewthree3** [comment] 2021-08-05 20:12
I don’t have a clue either. If you’re looking to play mp3s on a 3DS though, limeplayer (I think it’s called that) is a great choice that I used before I got my switch and hacked it.
good luck man!

**Comment by obscurerev** [comment] 2021-08-05 20:14
I already have an mp3 player on my 3ds. I just want mp3's to play in PKSM.

**Comment by piepie62** [comment] 2021-08-05 20:30
Do they all follow these recommendations from the wiki? `Relatively small file sizes are recommended, as are sampling frequency of 44100Hz and a bitrate of 96kbps.` If so, I'd need to look deeper into this

**Comment by Mewthree3** [comment] 2021-08-05 20:34
As for filesize, mine usually ranged from 2-6MB.
I can’t check the sampling or bitrate however

**Comment by obscurerev** [comment] 2021-08-06 13:56
I can't check the sampling bit-rate on mine, but let me tell you that the same exact mp3 file worked before a couple of months, but then it just stopped working entirely, along with any mp3 I put in.

**Comment by piepie62** [comment] 2021-08-09 23:54
I'm not sure what could be causing that, then. I haven't changed the sound handling code since at at least 9.0.0, which released over a year ago. My best guesses are that it's something wrong with the MP3 or possibly your SD card

**Comment by obscurerev** [comment] 2022-07-20 16:31
even after nearly a year later, this issue is still a problem for me. I've tried wav, m4a, mp3 with album cover, mp3 without any album cover, songs that are not over a minute. nothing is working. It just plays for a second and cuts off.

**Comment by mayamcdougall** [comment] 2022-08-29 02:05
Just started having this issue the other day.  At first, I was worried it might be my SD card starting to fail, but that doesn't seem to be it.

I haven't made any changes to my PKSM setup, it's been exactly the same as it's always been (for several years), just suddenly now the music's broken.

So unless the 20 extra boxes of Pokemon I recently bred (in my attempt to learn to IV breed 😂) did something, I've got nothing to contribute here other than "same here". 😔

**Comment by obscurerev** [comment] 2022-09-02 01:32
hm I never thought of rehid interfering with this, will try this out

**Comment by obscurerev** [comment] 2022-09-05 14:58
doesn't work :(

**Comment by mayamcdougall** [comment] 2022-09-07 16:42
Did you make sure to either completely remove Rehid from `/luma/titles` or disable Game Patching in Luma's settings (hold select while booting your 3DS)?

Actually, disabling Game Patching *in general* would also be a good way to double check that there's nothing *else* that could be interfering with PKSM either too. 🤔

**Comment by GriffinG1** [comment] 2023-03-26 18:32
I am going to go ahead and tentatively close this now that [v10](https://github.com/FlagBrew/PKSM/releases/latest) has been released. @obscurerev if the issue persists in v10 please update here and I will reopen.

**Closed by GriffinG1** 2023-03-26 18:32 UTC
Labels: failed to reproduce

**Comment by mayamcdougall** [comment] 2023-03-26 20:13
First off, congrats on the new release, and thank you to the team for working on it!  I've been silently watching the commit history for the last year or more, waiting for the day that Gen 1/2 support might finally be released.

This is absolutely amazing! 😁

... but, I do also have to unfortunately confirm that this issue still occurs. 😒

In the comments above, @obscurerev never actually confirmed that they *fully* removed or disabled Rehid, or if they had any other Luma modules running.  So, I still suspect that this issue is related to that.  Rehid is a little difficult to remove, since Rehid Helper creates a lot of persistent files that could be easily overlooked.

It's probably out-of-scope to even fix this bug unless there's an obvious cause (eg, some kind of oversight), since it seems to be triggered by other homebrew running.

Anyway, not complaining, just trying to keep things documented. 😉

Congrats again on the v10 release! 🎉❤️

**Comment by obscurerev** [comment] 2023-03-26 21:20
I am glad to say that deleting the rehid folder actually fixed the issue. I'm sorry for this late response, but I thank everyone who has helped me with this issue. Also congrats on 10.0 🥳

**Comment by mayamcdougall** [comment] 2023-03-30 19:27
Cool, so it's officially narrowed down to a compatibility issue with Rehid.

Now... if only we could have *both*... 👀😅
