### ISSUE TITLE
Many problems, please read.

### ISSUE THREAD

**Issue by StoneRSol** [FlagBrew/PKSM#907] opened 2019-02-01 03:58 UTC
*No release in editor mode.

*When choosing moves, it doesn't keep your place like it does for the previous version.

*Genderless pokemon have genders.

*I created a pokemon (lvl 1 buneary) and it had the following legality errors on PKHEX,
- invalid relearn move 1,2,3,4
- unable to match encounter with origin name
- nickname does not match species name
- language ID should be <=ChineseT, not Hacked
- geolocation country is not in 3ds region
Note: i made the same exact buneary after going back to v5.1 and it is perfectly legal.

*Friendship reads 0/0 instead of 0/255

I hope you got a chance to read this. Thanks for putting in all the time and effort

**Comment by SpiredMoth** [comment] 2019-02-01 05:00
In regards to relearn moves, I think the problem is the *lack* of them -- anything from an egg (maybe anything period) in Gen 6+ should have at least one relearn move (see Bulbapedia's [Move Reminder page](https://bulbapedia.bulbagarden.net/wiki/Move_Reminder#Teachable_moves) for details)

**Comment by piepie62** [comment] 2019-02-01 05:01
That... doesn't sound right. As far as I was aware, relearn moves are egg moves, so that the game knows that that Pokémon can "relearn" them if they are ever overwritten

**Comment by SpiredMoth** [comment] 2019-02-01 05:18
PKHeX would catch any egg moves, and before Gen 7 level-up moves from above it's current level, in the moveset and check for them also being under relearn moves and report any inconsistency.

**Comment by StoneRSol** [comment] 2019-02-01 05:53
Re: piepie
I put relearn moves on being as they are eggmoves. The move are legal but for some reason didnt register as so in game.

English language and english save.

Ill reinstall 6.0.1 on my other DS and see if there is something in options i didnt do right

**Comment by piepie62** [comment] 2019-03-04 20:13
Reading through this issue, it seems that most of the problems are either fixed or invalid. Closing; if you have any problems with 6.1.1 make a new issue for them separately, please.

**Closed by piepie62** 2019-03-04 20:13 UTC
