### ISSUE TITLE
Qr Scan bug

### ISSUE THREAD

**Issue by aiueo0721** [FlagBrew/PKSM#1186] opened 2020-06-14 17:51 UTC
1 Press edit Press 
2R + L
3 An error has occurred.
If you press a at this point, the power turns off and the same operation does not make sense.
Pksmver.9.0.1
I'm cheering for a better tool.
![IMG00027](https://user-images.githubusercontent.com/66917584/84600264-0c7b2f00-aeb3-11ea-9c1a-c4938aac7c25.jpg)

**Comment by piepie62** [comment] 2020-06-14 17:59
Confirmed on latest release. Does not happen on latest nightly. There are two options: either I somehow fixed this at some point, or it's to do with differing compiler flags. I'll look into it.

**Comment by piepie62** [comment] 2020-06-14 20:00
Turns out it was compiler flags. That'll be fixed in the next release.

**Closed** 2020-06-21 19:56 UTC
Labels: bug, fixed
