### ISSUE TITLE
Feature Request - Either early PSS unlock, or unlock Petalburg City Fly location

### ISSUE THREAD

**Issue by AlternisDim20** [FlagBrew/PKSM#1300] opened 2021-10-07 01:13 UTC
XY unlocked the PSS, and with it Super Training and Pokemon-Amie and O-Powers, at the very start of the game; ORAS instead made all this unavailable until Petalburg is reached and Wally is helped, meaning no access to these very useful features until after multiple Trainer battles are done.

One solution is to add a script to unlock the PSS early, so the Starter Pokemon can be Super Trained, and fed Poke Puffs, and the Prize Money O-Power can be used, before battling May.

An alternative solution is to add a different script, similar to the "Unlock Battle Resort Fly Location" script that's built-in, that allows Flying to Petalburg City. This would also require the Eon Flute to be hacked in, though, in order to reach Petalburg early, since HM02 Fly is obtained significantly later (and the ability to use the move Fly outside of battle, just a bit later than that).

**Comment by SpiredMoth** [comment] 2021-10-07 01:20
Duplicate of your post in the [PKSM-Scripts suggestions issue](https://github.com/FlagBrew/PKSM-Scripts/issues/3#issuecomment-937288508)

**Closed by SpiredMoth** 2021-10-07 01:20 UTC
