### ISSUE TITLE
Gender issue when generating from the editor

### ISSUE THREAD

**Issue by CloudOfMist** [FlagBrew/PKSM#916] opened 2019-02-10 08:58 UTC
When i generate a legendary pokemon on PKSM 6.1.0 (for example Mew) it has gender!!

**Comment by TLATER** [comment] 2019-02-10 13:53
This is a duplicate of #849, see why this happens there.

Please search through the closed issues before creating an issue.

**Comment by CloudOfMist** [comment] 2019-02-11 07:27
I will. Thank you kind sir!


Στις Κυρ, 10 Φεβ 2019 - 15:53 ο χρήστης Tristan Maat <
notifications@github.com> έγραψε:

**Closed** 2019-02-12 01:37 UTC
