### ISSUE TITLE
Pokemon Crystal (VC) Pokemon is removed from box

### ISSUE THREAD

**Issue by Gronis** [FlagBrew/PKSM#1409] opened 2023-08-01 23:39 UTC
**Describe the bug**
Trying to put any pokemon into my crystal version (VC on 3ds), but pokemon is removed when checking the box in-game.

I wanted to try to move pokemon from newer generations into my gen 2 VC, so I tried duping a Chikorita that had on Pkmn Black 2. (lvl 5) tackle + growl. The procedure seemed to work. I have pressed the save button and crystal starts. Now had 3 in my pokedex: cyndaquil (starter) + hoothoot (first catch) + chikorita. However only hoothoot was in the box. 

I go back into the box and duplicate hoothoot on the crystal VC using PKSM. Same thing happens, just the original hoothoot, no cloned pokemon in sight.

Now, I try the same procedure on Pokemon Blue VC, but with an abra with just teleport (from my black 2 game) instead of Chikorita. This works flawlessly.

Finally, I copy a pidgey I caught in Pokemon Blue and move that to Crystal. The same thing happens. I have Pidgey in my pokedex (as caught, was not caught previously), but no pidgey in the box.

**To Reproduce**
1. Start new game on crystal
2. Catch a pokemon
3. Add catched pokemon to box 1
4. Start PKSM with crystal VC
5. Click on 'Storage'
6. Duplicate newly catched pokemon
7. Go back and click the up arrow in the bottom left corner to save the data to pokemon crystal VC
8. When Crystal starts, observe that there is only 1 copy of your catched pokemon in the box.

**Expected behavior**
Cloned Pokemon should be in box 1 just together with the original pokemon

**Information about your environment**
 - OS version: 11.17.0-50E
 - PKSM version: 10.0.0

**Comment by GriffinG1** [comment] 2023-08-01 23:41
Looks to be duplicate of #1374. Closing.

**Closed by GriffinG1** 2023-08-01 23:41 UTC
